---
- name: Update web servers
  hosts: "{{ variable_host | default('all') }}"
  gather_facts: false
  remote_user: root

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: full

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
